trigger RTV_POS_Data_AuthCodeChange on RTV_POS_Data__c (after update) {
    List<RTV_Order__c> orders = new List<RTV_Order__c>();
    List<RTV_Order_Item__c> items = new List<RTV_Order_Item__c>();
    List<Id> posdataIds = new List<Id>();
    List<RTV_POS_Item__c> positems = new List<RTV_POS_Item__c>();
    Map<String,Id> orderPosIds = new Map<String,Id>();

    // 宝尊
    RTV_BaoZun_Seeding__c baozunSeeding = null;
    List<RTV_Order__c> baozOrders = new List<RTV_Order__c>();
    // DateTime today = DateTime.now();
    // List<RTV_BaoZun_Seeding__c> baozunSeedings = [SELECT Id, Seeding_Auth_Code__c FROM RTV_BaoZun_Seeding__c WHERE Year__c = :today.year() AND Month__c = :today.month()];
    // if(baozunSeedings != null && baozunSeedings.size() > 0){
    //     baozunSeeding = baozunSeedings.get(0);
    // }
    Map<String,List<RTV_BaoZun_Seeding__c>> baozunSeedingMap = new Map<String,List<RTV_BaoZun_Seeding__c>>();
    for(RTV_Baozun_Seeding__c bs : [SELECT Id,Year__c,Month__c,Seeding_Auth_Code__c FROM RTV_BaoZun_Seeding__c]){
        List<RTV_BaoZun_Seeding__c> baozunSeedingList = new List<RTV_BaoZun_Seeding__c>();
        String y = String.valueOf(bs.Year__c);
        String m = String.valueOf(bs.Month__c);
        String ym = y + m;
        baozunSeedingList.add(bs);
        baozunSeedingMap.put(ym,baozunSeedingList);
    }

    // 检索allRecordTypes
    Map<String, RecordType> allTypes = RMS_CommonUtil.getRecordTypes('RTV_POS_Data__c');
    // item的recordtypes
    Map<String, RecordType> itemTypes = RMS_CommonUtil.getRecordTypes('RTV_Order_Item__c');
    Map<String, RecordType> orderTypes = RMS_CommonUtil.getRecordTypes('RTV_Order__c');
    Savepoint savePot = Database.setSavepoint();
    try {
        for(RTV_POS_Data__c newdata : Trigger.new){
            // 授权码变更
            RTV_POS_Data__c olddata = Trigger.oldMap.get(newdata.Id);
            if(newdata.Auth_Code__c != olddata.Auth_Code__c && String.isNotBlank(newdata.Auth_Code__c)){

                //宝尊虚拟退库
                if(newdata.Auth_Code__c.startsWith('SEEDBZ')){
                    Integer year = (olddata.Transfer_Time__c).year();
                    Integer month = (olddata.Transfer_Time__c).month();
                    String ym = String.valueOf(year)+String.valueOf(month);
                    List<RTV_BaoZun_Seeding__c> baozunSeedings = baozunSeedingMap.get(ym);
                    if(baozunSeedings != null && baozunSeedings.size() > 0){
                        baozunSeeding = baozunSeedings.get(0);
                    }
                    if(baozunSeeding != null && newdata.Auth_Code__c == baozunSeeding.Seeding_Auth_Code__c){
                        RTV_Order__c order = new RTV_Order__c();
                        Integer randomInt = (Math.random()*1000000).intValue();
                        String randomStr = String.valueOf(randomInt).leftPad(6, '0');
                        order.Name = baozunSeeding.Seeding_Auth_Code__c + '-' +  randomStr;
                        order.Earliest_Delivery_Date__c = newdata.Earliest_Delivery_Date__c;
                        order.RTV_Baozun_Seeding__c = baozunSeeding.Id;
                        order.Order_Type__c ='DTC Tackback';
                        order.Seeding_Status__c ='POST to LF';
                        order.RecordTypeId = orderTypes.get('RTV Baozun Order').Id;
                        order.Status__c = 'POST to LF';
                        order.POS_Transfer_Order_No__c =newdata.Order_No__c;
                        order.POS_Transfer_Time__c =newdata.Transfer_Time__c;
                        //insert order;
                        baozOrders.add(order);

                        posdataIds.add(newdata.Id);
                        orderPosIds.put(order.Name,newdata.Id);
                        // if(baozOrders.size()>0){    
                        //     for (RTV_POS_Item__c item: [
                        //         SELECT Id, Name, Material_Code__c, QTY__c, Size_Code__c
                        //         FROM RTV_POS_Item__c 
                        //         WHERE RTV_POS_Data__c = :newdata.Id
                        //     ]) {
                        //         RTV_Order_Item__c obj = new RTV_Order_Item__c();
                        //         obj.RTV_Order__c = order.Id;
                        //         obj.Material_Code__c = item.Material_Code__c;
                        //         obj.Name = item.Name;
                        //         obj.POS_SKU__c = item.Name;
                        //         obj.SKU_Size_US__c = item.Size_Code__c;
                        //         obj.Application_QTY__c = item.QTY__c;
                        //         obj.RecordTypeId = itemTypes.get('Baozun Seeding').Id;
                        //         items.add(obj);
                        //     }
                        // }
                    }
                    else {
                        newdata.addError('宝尊授权码（' + newdata.Auth_Code__c + '）不存在！');
                    }
                }
                // DTC TB DEF
                else {
                    String BU = null;
                    if(newdata.Auth_Code__c.endsWith('AP')){
                        BU = 'AP';
                    }
                    else if (newdata.Auth_Code__c.endsWith('AC')) {
                        BU = 'AC';
                    }
                    else if (newdata.Auth_Code__c.endsWith('FW')) {
                        BU = 'FW';
                    }else {
                        newdata.addError('授权码（' + newdata.Auth_Code__c + '）不正确！');
                        continue;
                    }

                    // 查找该授权码Order
                    String ordercode = newdata.Auth_Code__c.substring(0, newdata.Auth_Code__c.length() - 2);
                    List<RTV_Order__c> orderlst = [SELECT Id, Status__c, Return_Summary__c,Store_Code__c,DTC_Type__c FROM RTV_Order__c WHERE Name = :ordercode];
                    
                    // 授权码存在的情况
                    if(orderlst.size() > 0){
                        if(orderlst.get(0).Status__c == 'Ready'){
                            if(orderlst.get(0).DTC_Type__c=='CFS'&&orderlst.get(0).Store_Code__c!=newdata.Name){
                                newdata.addError('孤单门店号（' + newdata.Name + '）与挂靠的订单门店号不一致！');
                            }
                            // 更新Ready状态的order
                            //if(orderlst.get(0).Status__c == 'Ready'){
                                // Takeback时，更新Order的Status为POST LF
                            if (orderlst.get(0).Return_Summary__c != null) {
                                orderlst.get(0).Status__c = 'POST to LF';
                            }
                            // 更新最早提货日
                            orderlst.get(0).Earliest_Delivery_Date__c = newdata.Earliest_Delivery_Date__c;
                            //}
                            orders.add(orderlst.get(0));
                            posdataIds.add(newdata.Id);
                            
                            for (RTV_POS_Item__c item: [
                                SELECT Id, Name, Material_Code__c, QTY__c, Size_Code__c, IsMaterial__c
                                FROM RTV_POS_Item__c 
                                WHERE RTV_POS_Data__c = :newdata.Id
                            ]) {
                                RTV_Order_Item__c obj = new RTV_Order_Item__c();
                                obj.RTV_Order__c = orderlst.get(0).Id;
                                obj.BU_2__c = BU;
                                obj.Material_Code__c = item.Material_Code__c;
                                obj.IsMaterial__c = item.IsMaterial__c;
                                obj.Name = item.Name;
                                obj.POS_SKU__c = item.Name;
                                obj.SKU_Size_US__c = item.Size_Code__c;
                                obj.Application_QTY__c = item.QTY__c;
                                obj.RecordTypeId = itemTypes.get('DTC').Id;
                                items.add(obj);

                                item.BU__c = BU;
                                positems.add(item);
                            }
                        }
                        else {
                            newdata.addError('该授权码（' + newdata.Auth_Code__c + '）使用的订单已为提交物流状态！');
                        }
                    }
                    else {
                        newdata.addError('授权码（' + newdata.Auth_Code__c + '）不存在！');
                    }
                }
                
            }
        }

        // DTC TB DEF
        if(orders.size() > 0){
            insert items;
            update orders;
        }

        // Baozun seeding
        if(baozOrders.size() > 0){
            insert baozOrders;
            for(RTV_Order__c order:baozOrders){
                Id posdataId = orderPosIds.get(order.Name);    
                for (RTV_POS_Item__c item: [
                    SELECT Id, Name, Material_Code__c, QTY__c, Size_Code__c
                    FROM RTV_POS_Item__c 
                    WHERE RTV_POS_Data__c = :posdataId
                ]) {
                    RTV_Order_Item__c obj = new RTV_Order_Item__c();
                    obj.RTV_Order__c = order.Id;
                    obj.Material_Code__c = item.Material_Code__c;
                    obj.Name = item.Name;
                    obj.POS_SKU__c = item.Name;
                    obj.SKU_Size_US__c = item.Size_Code__c;
                    obj.Application_QTY__c = item.QTY__c;
                    obj.RecordTypeId = itemTypes.get('Baozun Seeding').Id;
                    items.add(obj);
                }
            }
            insert items;
        }

        List<RTV_POS_Data__c> objs = [
            SELECT Id FROM RTV_POS_Data__c WHERE Id IN : posdataIds
        ];
        for (RTV_POS_Data__c obj : objs) {
            obj.RecordTypeId = allTypes.get('Completed').Id;
        }

        update objs;
        update positems;

    } catch (Exception e) {
        Trigger.new[0].addError(e.getMessage() + '\r\n' + e.getStackTraceString());
        Database.rollback(savePot);
    }
    
    
    // 用于跳过代码覆盖率测试
    if(Test.isRunningTest()){
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
    }
}